server {
	listen 80;
	server_name lk.site.ru;

    location / {
        root /var/www/lksite;
		index   index.html
    }
}

server {
	listen 80;
	server_name site.ru;

    location / {
        	root /var/www/mpsite;
			index   index.html
    }
}